// Community & Supabase Integration Logic
// IMPORTANT: To make the backend work, you need to create a Supabase account at https://supabase.com
// 1. Create a new project.
// 2. Go to Project Settings -> API and copy your URL and ANON KEY here.
// 3. In the SQL Editor, run:
/*
  create table resources (
    id bigint generated by default as identity primary key,
    title text,
    type text,
    branch text,
    semester text,
    subject text,
    url text,
    uploader_roll text,
    approved boolean default false,
    created_at timestamp with time zone default timezone('utc'::text, now())
  );
  
  create table profiles (
    roll_number text primary key,
    points integer default 0
  );
*/

const SUPABASE_URL = 'https://vjotaxbxvigxldockvdd.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZqb3RheGJ4dmlneGxkb2NrdmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQ0MzMxODcsImV4cCI6MjEwMDAwOTE4N30.U_Xhk6nIV3oizux7Iy0vauoK8ztGWoklCnyfwI2eEdg';

// Initialize Supabase Client (Will be null if keys not provided)
const supabase = SUPABASE_URL.startsWith('http') ? window.supabase.createClient(SUPABASE_URL, SUPABASE_KEY) : null;

document.addEventListener('DOMContentLoaded', () => {
    // Populate profile if data available
    const rollSpan = document.getElementById('profRoll');
    const nameSpan = document.getElementById('profName');

    if (window.data && window.data.home?.summary) {
        rollSpan.textContent = localStorage.getItem('bb_roll_id') || localStorage.getItem('bb_roll') || 'Unknown';
        nameSpan.textContent = window.data.name || 'Student';
    }

    // Handle Upload resource
    const uploadForm = document.getElementById('resourceUploadForm');
    if (uploadForm) {
        uploadForm.addEventListener('submit', async (e) => {
            e.preventDefault();
            const title = document.getElementById('resTitle').value;
            const type = document.getElementById('resType').value;
            const branch = document.getElementById('resBranch').value;
            const sem = document.getElementById('resSem').value;
            const subject = document.getElementById('resSubject')?.value || '';
            const url = document.getElementById('resUrl').value;
            const roll = localStorage.getItem('bb_roll_id') || localStorage.getItem('bb_roll') || 'Unknown';

            if (!supabase) {
                alert("Upload recorded locally! Admin must set SUPABASE_URL in js/community.js to save to cloud.");
                document.getElementById('uploadStatus').style.display = 'block';
                return;
            }

            try {
                // DB Insert
                const { data, error } = await supabase
                    .from('resources')
                    .insert([{ title, type, branch, semester: sem, subject, url, uploader_roll: roll, approved: false }]);

                if (error) throw error;

                document.getElementById('uploadStatus').textContent = "Upload successful! Waiting for admin approval (+50 BP pending).";
                document.getElementById('uploadStatus').style.display = 'block';
                uploadForm.reset();
                loadCommunityFeed();
            } catch (err) {
                alert("Upload failed: " + err.message);
            }
        });
    }

    // Attach filter listeners
    ['filterSem', 'filterBranch', 'filterSubject'].forEach(id => {
        const el = document.getElementById(id);
        if (el) el.addEventListener('change', loadCommunityFeed);
    });

    // Load Data
    loadCommunityFeed();
    fetchMyPoints();
});

async function loadCommunityFeed() {
    const feed = document.getElementById('communityFeed');
    if (!feed || !supabase) return;

    try {
        const myRoll = localStorage.getItem('bb_roll_id') || localStorage.getItem('bb_roll') || '';
        let orQuery = 'approved.eq.true';
        if (myRoll) {
            orQuery += `,uploader_roll.eq.${myRoll}`;
        }

        let query = supabase.from('resources').select('*');
        query = query.or(orQuery);

        // Apply filters
        const fs = document.getElementById('filterSem')?.value;
        const fb = document.getElementById('filterBranch')?.value;
        const fr = document.getElementById('filterSubject')?.value;
        if (fs && fs !== 'all') query = query.eq('semester', fs);
        if (fb && fb !== 'all') query = query.eq('branch', fb);
        if (fr && fr !== 'all') query = query.eq('subject', fr);

        const { data, error } = await query
            .order('created_at', { ascending: false })
            .limit(20);

        if (error) throw error;

        if (data && data.length > 0) {
            // Update Select dropdowns dynamically
            const uniqueSubjects = [...new Set(data.map(d => d.subject).filter(Boolean))];
            
            const datalist = document.getElementById('resSubjectList');
            if (datalist && datalist.options.length === 0) {
                 datalist.innerHTML = uniqueSubjects.map(s => `<option value="${s}">`).join('');
            }
            
            const subjSelect = document.getElementById('filterSubject');
            if (subjSelect && subjSelect.options.length <= 1) {
                 const currVal = subjSelect.value;
                 subjSelect.innerHTML = '<option value="all">All Subjects</option>' + uniqueSubjects.map(s => `<option value="${s}">${s}</option>`).join('');
                 subjSelect.value = currVal;
            }

            feed.innerHTML = data.map(item => {
                const isPending = !item.approved;
                const badgeHtml = isPending 
                    ? `<span style="background: rgba(245, 158, 11, 0.2); color: #fcd34d; font-size: 0.65rem; padding: 2px 8px; border-radius: 99px; margin-left: 8px; border: 1px solid rgba(245, 158, 11, 0.3); vertical-align: middle;">Pending</span>`
                    : '';
                    
                const linkAction = isPending 
                    ? `<div style="font-size:0.75rem; color: #f59e0b; text-align:right;">Awaiting<br>Approval</div>`
                    : `<a href="${item.url}" target="_blank" class="solid-btn" style="padding: 8px 15px; background: rgba(56, 189, 248, 0.1); color: #38bdf8; border: none; font-size: 0.8rem; text-decoration: none;">View ${item.type}</a>`;

                const subjectText = item.subject ? ` | ${item.subject}` : '';

                return `
                <div style="background: rgba(255,255,255,0.02); border: 1px solid rgba(255,255,255,0.05); padding: 15px; border-radius: 12px; display: flex; justify-content: space-between; align-items: center; opacity: ${isPending ? '0.6' : '1'}; transition: 0.3s;">
                    <div>
                        <div style="font-weight: bold; color: #fff; margin-bottom: 5px; display: flex; align-items: center;">${item.title} ${badgeHtml}</div>
                        <div style="font-size: 0.8rem; color: var(--text-muted); font-family: var(--font-mono);">${item.branch} | Sem ${item.semester}${subjectText}</div>
                    </div>
                    ${linkAction}
                </div>`;
            }).join('');
        } else {
            feed.innerHTML = `<div class="empty-state">No approved resources yet. Be the first to upload!</div>`;
        }
    } catch (err) {
        console.warn("Could not load resources:", err);
    }
}

async function fetchMyPoints() {
    const myPoints = document.getElementById('profPoints');
    const claimBtn = document.getElementById('claimTeaBtn');
    if (!supabase || !myPoints) return;

    try {
        const myRoll = localStorage.getItem('bb_roll_id') || localStorage.getItem('bb_roll');
        if (!myRoll) return;

        // Dynamically calculate points: 50 points per approved upload
        const { count, error } = await supabase
            .from('resources')
            .select('*', { count: 'exact', head: true })
            .eq('uploader_roll', myRoll)
            .eq('approved', true);

        if (count !== null && !error) {
            const points = count * 50;
            myPoints.textContent = points;

            // Check if user hit 500
            if (points >= 500 && claimBtn) {
                claimBtn.disabled = false;
                claimBtn.style.background = '#f59e0b';
                claimBtn.style.color = '#000';
                claimBtn.style.cursor = 'pointer';
                claimBtn.onclick = () => alert("🎉 FREE CHAI UNLOCKED!\n\nCoupon Code: BUNK-MVP-2026\nShow this code to the admin to claim your reward.");
            }
        }
    } catch (err) {
        console.warn("Could not load points:", err);
    }
}
